### ISSUE TITLE
Failed to configure Superwall

### ISSUE THREAD

**Issue by robss88** [superwall-me/Superwall-Flutter#2]
I randomly run into this error about 75% of the time when launching my app. Sometimes the superwall configures perfectly and the rest it comes back with this error and my pay wall won't show up anymore

flutter: Failed to configure Superwall: MissingPluginException(No implementation found for method configure on channel SuperwallBridge-e4a4029f-5346-4fe8-b6c0-fcee29cf47f7)

**Comment by super-bryan** [comment]
Hi @robss88, thanks for reporting that. This should be fixed in 0.0.6 – please be aware that Flutter for Superwall is in a developer preview state and not yet ready for production apps. We'll have more to announce by email later this week!
