### ISSUE TITLE
[Build Failed] Can't build with version 1.0.0 in Flutter

### ISSUE THREAD

**Issue by harrylefit** [superwall-me/Superwall-Flutter#5]
Hi,
I'm trying to upgrade to version 1.0.0 in Flutter but I can't build it. It works okay with version 0.0.27. You can check logs with my attachment.
<img width="1093" alt="image" src="https://github.com/superwall-me/Superwall-Flutter/assets/20136040/957d03c2-7560-49d5-a47b-0bbb653d55e4">

[logs.txt](https://github.com/superwall-me/Superwall-Flutter/files/14544351/logs.txt)

**Comment by yusuftor** [comment]
Thanks for reporting. This looks like a breaking change to the imports of some classes that was made in Android v1.0 wasn't carried through to the Flutter SDK. I'll fix this on Monday, sorry about that!

**Comment by yusuftor** [comment]
This is fixed now in v1.0.1
